export const ActionTypes = {
  FETCH_USERS: 'FETCH_USERS',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
  FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
  PERSIST_USER_SUCCESS: 'PERSIST_USER_SUCCESS',

  FETCH_COURSES: 'FETCH_COURSES',
  FETCH_COURSES_SUCCESS: 'FETCH_COURSES_SUCCESS',
  FETCH_COURSES_FAILURE: 'FETCH_COURSES_FAILURE',
  PERSIST_COURSES_SUCCESS: 'PERSIST_COURSE_SUCCESS',
};
